package application2

import (
	"context"
	"fmt"
	"meet-attendance-clean/domain2/student"
	"time"
)

// 1. PORTS
type SyncConfigRepo interface {
	GetLastSyncTime(ctx context.Context) (*time.Time, error)
	UpdateLastSyncTime(ctx context.Context, t time.Time) error
}

type GoogleWorkspaceGateway interface {
	FetchMeetingsFrom(ctx context.Context, fromTime time.Time) ([]*student.ClassSession, error)
}

type ClassSessionRepo interface {
	SaveBatch(ctx context.Context, sessions []*student.ClassSession) error
}

// 2. USECASE
type SyncMeetingUsecase struct {
	syncRepo    SyncConfigRepo
	meetGateway GoogleWorkspaceGateway
	sessionRepo ClassSessionRepo
	studentRepo StudentRepo
}

func NewSyncMeetingUsecase(
	syncRepo SyncConfigRepo,
	meetGateway GoogleWorkspaceGateway,
	sessionRepo ClassSessionRepo,
	studentRepo StudentRepo,
) *SyncMeetingUsecase {
	return &SyncMeetingUsecase{
		syncRepo:    syncRepo,
		meetGateway: meetGateway,
		sessionRepo: sessionRepo,
		studentRepo: studentRepo,
	}
}

func (u *SyncMeetingUsecase) Sync(ctx context.Context) error {

	syncFrom := u.determineSyncStartTime(ctx)

	rawSessions, err := u.meetGateway.FetchMeetingsFrom(ctx, syncFrom)
	if err != nil {
		return fmt.Errorf("lỗi khi kéo dữ liệu Google Meet: %w", err)
	}

	var validSessions []*student.ClassSession
	var newStudents []*student.Student

	// Bước 3: Áp dụng luật nghiệp vụ (Điều phối)
	for _, session := range rawSessions {
		// Yêu cầu Domain kiểm tra: Lớp học có trống không?
		// if session.IsEmpty() {
		// 	continue // Bỏ qua phiên học không ai tham gia
		// }

		validSessions = append(validSessions, session)

		// Kiểm tra xem Học sinh (SpaceID) này đã có trong hệ thống chưa
		exists, err := u.studentRepo.ExistsBySpaceID(ctx, session.SpaceID())
		if err != nil {
			return fmt.Errorf("lỗi kiểm tra tồn tại học sinh: %w", err)
		}

		if !exists {
			// Yêu cầu Domain TỰ TẠO ra một học sinh ẩn danh từ dữ liệu Meet
			newStudent := student.NewAutoGeneratedStudentFromMeet(
				session.SpaceID(),
				session.SpaceName(),
				session.MeetingCode(),
			)
			newStudents = append(newStudents, newStudent)
		}
	}

	// Bước 4: Lưu kết quả xuống Database
	// (Tùy chiến lược: Lưu từng đứa hoặc viết 1 hàm Repo lưu chung trong 1 Transaction)
	for _, stu := range newStudents {
		if err := u.studentRepo.Save(ctx, stu); err != nil {
			return fmt.Errorf("lỗi lưu học sinh mới tự sinh: %w", err)
		}
	}

	if len(validSessions) > 0 {
		if err := u.sessionRepo.SaveBatch(ctx, validSessions); err != nil {
			return fmt.Errorf("lỗi lưu batch phiên học: %w", err)
		}
	}

	// Bước 5: Cập nhật thời điểm Sync cuối cùng
	now := time.Now().UTC()
	_ = u.syncRepo.UpdateLastSyncTime(ctx, now)

	return nil
}

// Logic tính toán thời gian tách riêng cho dễ đọc/test
func (u *SyncMeetingUsecase) determineSyncStartTime(ctx context.Context) time.Time {
	lastSync, err := u.syncRepo.GetLastSyncTime(ctx)
	if err != nil || lastSync == nil {
		// Trắng data: Kéo lại dữ liệu của 3 tháng qua
		return time.Now().UTC().AddDate(0, -3, 0)
	}
	// Có data: Kéo lùi lại 3 ngày để đề phòng Google API bị delay log
	return lastSync.AddDate(0, 0, -3)
}
