// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectGoogleMeet() {
  return window['go']['main']['App']['ConnectGoogleMeet']();
}

export function ConnectOneNote() {
  return window['go']['main']['App']['ConnectOneNote']();
}

export function DisconnectGoogleMeet() {
  return window['go']['main']['App']['DisconnectGoogleMeet']();
}

export function IsGoogleConnected() {
  return window['go']['main']['App']['IsGoogleConnected']();
}

export function IsOneNoteConnected() {
  return window['go']['main']['App']['IsOneNoteConnected']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function SetApplication2Services(arg1) {
  return window['go']['main']['App']['SetApplication2Services'](arg1);
}

export function V2CreateLesson(arg1) {
  return window['go']['main']['App']['V2CreateLesson'](arg1);
}

export function V2CreateLessonFromPDF(arg1) {
  return window['go']['main']['App']['V2CreateLessonFromPDF'](arg1);
}

export function V2GenerateRemediation(arg1) {
  return window['go']['main']['App']['V2GenerateRemediation'](arg1);
}

export function V2GetAssignment(arg1) {
  return window['go']['main']['App']['V2GetAssignment'](arg1);
}

export function V2GetDashboard(arg1) {
  return window['go']['main']['App']['V2GetDashboard'](arg1);
}

export function V2GetDocument(arg1) {
  return window['go']['main']['App']['V2GetDocument'](arg1);
}

export function V2GetDocumentPreview(arg1, arg2) {
  return window['go']['main']['App']['V2GetDocumentPreview'](arg1, arg2);
}

export function V2GetLessonDraft(arg1) {
  return window['go']['main']['App']['V2GetLessonDraft'](arg1);
}

export function V2GetStudentDetail(arg1) {
  return window['go']['main']['App']['V2GetStudentDetail'](arg1);
}

export function V2GradeAssignment(arg1) {
  return window['go']['main']['App']['V2GradeAssignment'](arg1);
}

export function V2ListAIModels() {
  return window['go']['main']['App']['V2ListAIModels']();
}

export function V2ListAssignments(arg1) {
  return window['go']['main']['App']['V2ListAssignments'](arg1);
}

export function V2ListDocuments() {
  return window['go']['main']['App']['V2ListDocuments']();
}

export function V2ListLessonDrafts() {
  return window['go']['main']['App']['V2ListLessonDrafts']();
}

export function V2ListMistakes() {
  return window['go']['main']['App']['V2ListMistakes']();
}

export function V2ListStudentChoices() {
  return window['go']['main']['App']['V2ListStudentChoices']();
}

export function V2PreparePublishing(arg1) {
  return window['go']['main']['App']['V2PreparePublishing'](arg1);
}

export function V2PublishLesson(arg1) {
  return window['go']['main']['App']['V2PublishLesson'](arg1);
}

export function V2PushAssignmentFeedback(arg1) {
  return window['go']['main']['App']['V2PushAssignmentFeedback'](arg1);
}

export function V2SaveLessonDraft(arg1) {
  return window['go']['main']['App']['V2SaveLessonDraft'](arg1);
}

export function V2SyncMeetings() {
  return window['go']['main']['App']['V2SyncMeetings']();
}

export function V2UpdateStudent(arg1) {
  return window['go']['main']['App']['V2UpdateStudent'](arg1);
}

export function V2UploadDocument() {
  return window['go']['main']['App']['V2UploadDocument']();
}
