// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {application2} from '../models';

export function ConnectGoogleMeet():Promise<void>;

export function ConnectOneNote():Promise<void>;

export function DisconnectGoogleMeet():Promise<void>;

export function IsGoogleConnected():Promise<boolean>;

export function IsOneNoteConnected():Promise<boolean>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function SetApplication2Services(arg1:main.Application2Services):Promise<void>;

export function V2CreateLesson(arg1:application2.GenerateLessonRequest):Promise<string>;

export function V2CreateLessonFromPDF(arg1:application2.GenerateLessonRequest):Promise<string>;

export function V2GenerateRemediation(arg1:application2.RemediationRequest):Promise<string>;

export function V2GetAssignment(arg1:string):Promise<application2.AssignmentDetailView>;

export function V2GetDashboard(arg1:application2.DashboardRequest):Promise<application2.DashboardView>;

export function V2GetDocument(arg1:string):Promise<application2.DocumentView>;

export function V2GetDocumentPreview(arg1:string,arg2:number):Promise<string>;

export function V2GetLessonDraft(arg1:string):Promise<application2.DraftView>;

export function V2GetStudentDetail(arg1:application2.StudentDetailRequest):Promise<application2.StudentDetailView>;

export function V2GradeAssignment(arg1:application2.GradeRequest):Promise<void>;

export function V2ListAIModels():Promise<Array<application2.ModelView>>;

export function V2ListAssignments(arg1:string):Promise<Array<application2.AssignmentSummary>>;

export function V2ListDocuments():Promise<Array<application2.DocumentView>>;

export function V2ListLessonDrafts():Promise<Array<application2.DraftView>>;

export function V2ListMistakes():Promise<Array<application2.StudentMistakeGroup>>;

export function V2ListStudentChoices():Promise<Array<application2.StudentView>>;

export function V2PreparePublishing(arg1:application2.PreparePublishingRequest):Promise<application2.PublishingTargets>;

export function V2PublishLesson(arg1:application2.PublishLessonRequest):Promise<void>;

export function V2PushAssignmentFeedback(arg1:string):Promise<void>;

export function V2SaveLessonDraft(arg1:application2.SaveLessonDraftRequest):Promise<void>;

export function V2SyncMeetings():Promise<void>;

export function V2UpdateStudent(arg1:application2.UpdateStudentRequest):Promise<void>;

export function V2UploadDocument():Promise<application2.DocumentView>;
