// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectGoogleMeet() {
  return window['go']['wails']['App']['ConnectGoogleMeet']();
}

export function ConnectOneNote() {
  return window['go']['wails']['App']['ConnectOneNote']();
}

export function CreateByPDf(arg1) {
  return window['go']['wails']['App']['CreateByPDf'](arg1);
}

export function CreateByUrl(arg1) {
  return window['go']['wails']['App']['CreateByUrl'](arg1);
}

export function SetApplication2Services(arg1) {
  return window['go']['wails']['App']['SetApplication2Services'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['App']['Startup'](arg1);
}

export function V2CreateLesson(arg1) {
  return window['go']['wails']['App']['V2CreateLesson'](arg1);
}

export function V2CreateLessonFromPDF(arg1) {
  return window['go']['wails']['App']['V2CreateLessonFromPDF'](arg1);
}

export function V2GenerateRemediation(arg1) {
  return window['go']['wails']['App']['V2GenerateRemediation'](arg1);
}

export function V2GetAssignment(arg1) {
  return window['go']['wails']['App']['V2GetAssignment'](arg1);
}

export function V2GetDashboard(arg1) {
  return window['go']['wails']['App']['V2GetDashboard'](arg1);
}

export function V2GetDocument(arg1) {
  return window['go']['wails']['App']['V2GetDocument'](arg1);
}

export function V2GetLessonDraft(arg1) {
  return window['go']['wails']['App']['V2GetLessonDraft'](arg1);
}

export function V2GetStudentDetail(arg1) {
  return window['go']['wails']['App']['V2GetStudentDetail'](arg1);
}

export function V2GradeAssignment(arg1) {
  return window['go']['wails']['App']['V2GradeAssignment'](arg1);
}

export function V2ListAIModels() {
  return window['go']['wails']['App']['V2ListAIModels']();
}

export function V2ListAssignments(arg1) {
  return window['go']['wails']['App']['V2ListAssignments'](arg1);
}

export function V2ListDocuments() {
  return window['go']['wails']['App']['V2ListDocuments']();
}

export function V2ListLessonDrafts() {
  return window['go']['wails']['App']['V2ListLessonDrafts']();
}

export function V2ListMistakes() {
  return window['go']['wails']['App']['V2ListMistakes']();
}

export function V2ListStudentChoices() {
  return window['go']['wails']['App']['V2ListStudentChoices']();
}

export function V2PreparePublishing(arg1) {
  return window['go']['wails']['App']['V2PreparePublishing'](arg1);
}

export function V2PublishLesson(arg1) {
  return window['go']['wails']['App']['V2PublishLesson'](arg1);
}

export function V2PushAssignmentFeedback(arg1) {
  return window['go']['wails']['App']['V2PushAssignmentFeedback'](arg1);
}

export function V2SyncMeetings() {
  return window['go']['wails']['App']['V2SyncMeetings']();
}

export function V2UpdateStudent(arg1) {
  return window['go']['wails']['App']['V2UpdateStudent'](arg1);
}

export function V2UploadDocument() {
  return window['go']['wails']['App']['V2UploadDocument']();
}
