// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';
import {application2} from '../models';

export function ConnectGoogleMeet():Promise<void>;

export function ConnectOneNote():Promise<void>;

export function CreateByPDf(arg1:wails.GenerateLessonRequest):Promise<string>;

export function CreateByUrl(arg1:wails.GenerateLessonRequest):Promise<string>;

export function SetApplication2Services(arg1:wails.Application2Services):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function V2CreateLesson(arg1:wails.GenerateLessonRequest):Promise<string>;

export function V2CreateLessonFromPDF(arg1:wails.GenerateLessonRequest):Promise<string>;

export function V2GenerateRemediation(arg1:wails.RemediationRequest):Promise<string>;

export function V2GetAssignment(arg1:string):Promise<application2.AssignmentDetailView>;

export function V2GetDashboard(arg1:wails.DashboardRequest):Promise<application2.DashboardView>;

export function V2GetDocument(arg1:string):Promise<application2.Document>;

export function V2GetLessonDraft(arg1:string):Promise<application2.DraftView>;

export function V2GetStudentDetail(arg1:wails.StudentDetailRequest):Promise<application2.StudentDetailView>;

export function V2GradeAssignment(arg1:wails.GradeRequest):Promise<void>;

export function V2ListAIModels():Promise<Array<wails.ModelView>>;

export function V2ListAssignments(arg1:string):Promise<Array<application2.AssignmentSummary>>;

export function V2ListDocuments():Promise<Array<application2.Document>>;

export function V2ListLessonDrafts():Promise<Array<application2.DraftView>>;

export function V2ListMistakes():Promise<Array<application2.StudentMistakeGroup>>;

export function V2ListStudentChoices():Promise<Array<application2.StudentView>>;

export function V2PreparePublishing(arg1:wails.PreparePublishingRequest):Promise<application2.PublishingTargets>;

export function V2PublishLesson(arg1:wails.PublishLessonRequest):Promise<void>;

export function V2PushAssignmentFeedback(arg1:string):Promise<void>;

export function V2SyncMeetings():Promise<void>;

export function V2UpdateStudent(arg1:wails.UpdateStudentRequest):Promise<void>;

export function V2UploadDocument():Promise<application2.Document>;
